### ISSUE TITLE
Using Data JPA Instead of Procedures

### ISSUE THREAD

**Issue by aandrey1993** [StefanBoblic/MAIBTestApp#2]
В описании задачи, был пункт что получения списка счетов должен делаться с помощью вызова хранимой процедуры:

`3. database - MS SQL, считывание счетов из DB - хранимая процедура`

В Вашей реализации для создания таблицы используется `Entity`  и встроенные методы `JpaRepository` для работы с данными.

Подскажите, пожалуйста, по какой причине был выбран данный подход ?

Сможете написать хранимую процедуру которая вернет список счетов по Вашей таблице `Sciot ` ? Sql код процедуры можете прикрепить в комментарии

**Comment by StefanBoblic** [comment]
Create Procedure CheckSciot as
Select ID as number, balance, currency,last_operation_time
from Sciot
(Я знаю что можно сделать Select * from)
У меня в скл файле такая процедура была,я проверял чтобы она работала,а вставить в код я ее не смог уже потмуо что я не знал куда ее можно впихнуть.Сейчас я понимаю как можно сделать-при помощи сервис класса,в данный момент я занимаюсь созданием методов для добавления,удаления,нахождения всех клиентов и одного клиента по айди:
![image](https://user-images.githubusercontent.com/57292223/133135119-d7066ce6-3bcf-48d7-bfa5-8af27d28b0bb.png)

**Comment by aandrey1993** [comment]
> 
> 
> Create Procedure CheckSciot as
> Select ID as number, balance, currency,last_operation_time
> from Sciot
> (Я знаю что можно сделать Select * from)
> У меня в скл файле такая процедура была,я проверял чтобы она работала,а вставить в код я ее не смог уже потмуо что я не знал куда ее можно впихнуть.Сейчас я понимаю как можно сделать-при помощи сервис класса,в данный момент я занимаюсь созданием методов для добавления,удаления,нахождения всех клиентов и одного клиента по айди:
> ![image](https://user-images.githubusercontent.com/57292223/133135119-d7066ce6-3bcf-48d7-bfa5-8af27d28b0bb.png)

Достаточно будет добавления процедуры для получения списка счетов. Не нужно написать для каждого метода, чтобы время не тратить на это. 

Вызов процедуры на получение списка счетов также нужно определить в репозитории. Для удобства, можете сделать отдельный репозиторий для работы с процедурой, чтобы продемонстрировать что получилось

**Comment by StefanBoblic** [comment]
ок,я как раз смотрю как это делается,я про @querry в репо

**Comment by aandrey1993** [comment]
И ещё, у вас от интерфейса Dao создается сервис. Это не правильно. Работа с Dao это всегда репозиторий:

![изображение](https://user-images.githubusercontent.com/49781313/133135981-bfcf0f3e-bd4a-4b6d-beb5-7cf05be0d15a.png)

В сервисе уже сделаете inject репозитория

**Comment by StefanBoblic** [comment]
Ок,получсется что все эти методы удаления добавления их можно удалить,потмуо что мне нужно только процедуру

**Comment by aandrey1993** [comment]
> 
> 
> Ок,получсется что все эти методы удаления добавления их можно удалить,потмуо что мне нужно только процедуру

Да, все правильно. Для вызова процедур средствами Spring, можете посмотреть в сторону `NamedParameterJdbcTemplate`

**Comment by StefanBoblic** [comment]
А есть средства не спринговские?Для меня способ с NamedParameterJdbcTemplate пока что безрезультатный

**Comment by aandrey1993** [comment]
С какими трудностями столкнулись при использовании `NamedParameterJdbcTemplate`  ?

**Comment by StefanBoblic** [comment]
Я вижу некоторые примеры которые используют бины, это раз
А два, появились еще такие классы как daoimplementation.Я правильно понимаю, что это те же сервисы? Или есть какое то отличие. И еще вопрос
Получается что сервис включает в себя дао, а контроллер включает сервис и я не понимаю почему я вчера неправильно сделал когда имплиментировал дао в сервис

**Comment by aandrey1993** [comment]
> 
> 
> Я вижу некоторые примеры которые используют бины, это раз
> А два, появились еще такие классы как daoimplementation.Я правильно понимаю, что это те же сервисы? Или есть какое то отличие. И еще вопрос
> Получается что сервис включает в себя дао, а контроллер включает сервис и я не понимаю почему я вчера неправильно сделал когда имплиментировал дао в сервис

Добрый день. Вы об этой имплиментации ?

![изображение](https://user-images.githubusercontent.com/49781313/133374490-919cd9ac-fa37-451b-8493-9573feb2cba3.png)

Вы на основе интерфейса Dao, определяете класс сервиса. Это не может быть сервисом, если вы в нем определяете логику получения данных из базы. Измените названия на ClientDaoImpl и поменяйте аннотацию на  `@Repository` вместо сервиса. 

`NamedParameterJdbcTemplate` должен автоматически определится на основе ваших настроек подключений к базе. Тут есть пример: https://mkyong.com/spring-boot/spring-boot-jdbc-examples/ (для my-sql, но для ms то же самое)

Так есть возможность ручной настройки, с помощью определения бина с установкой DataSource: https://stackoverflow.com/questions/44971320/how-do-i-manually-configure-a-jdbctemplate-in-spring-boot (Для `NamedParameterJdbcTemplate` смысл тот же)

**Comment by StefanBoblic** [comment]
Спасибо, когда приду после учебы буду делать

**Comment by StefanBoblic** [comment]
я закончил ,можете проверить пожалуйста

**Comment by aandrey1993** [comment]
По тому как вызывается процедура, все хорошо. 

Но не совпадает процедуру которую Вы оставили в комментариях с полями которые считываете из неё:

![изображение](https://user-images.githubusercontent.com/49781313/133833787-d8a8192a-edeb-41d8-b2b9-7c994043e453.png)

То что считывается из кода:

![изображение](https://user-images.githubusercontent.com/49781313/133833881-d9074f19-329f-443c-859c-367f87337a1b.png)


Поле Id процедура не возвращает. 
Наверное просто забыли прикрепить последний вариант

**Comment by StefanBoblic** [comment]
Да

**Comment by StefanBoblic** [comment]
А
я потом поменял процедуру,Я дропнул прошлую,ту что писал выше ,и сделал по новой
Create Procedure CheckSciot as
Select ID , number, balance, currency,last_operation_time
from Sciot
