### ISSUE TITLE
No intermediate DTO classes

### ISSUE THREAD

**Issue by aandrey1993** [StefanBoblic/MAIBTestApp#3]
Возвращение модели Entity (класс для работы с таблицей базы) внешнему API из контроллера, считается не самой хорошей практикой. Так как зачастую модель может содержать поля, про которых API не нужно знать. Также может быть такое что структура таблицы может поменяться.

Обычно для сериализации ответов в JSON и для получения входящих запросов, вводятся специальные классы DTO. В эти классы можно настроить аннотации Jackson для сериализации и управлять входящими параметрами API без рисков что-то задеть по базе. 

При получение данных из базы в Entity, пишется mapping который заполняет Dto объекты.
Попробуйте, пожалуйста, уйти от возвращение Entity из контроллера в сторону использования DTO

**Comment by StefanBoblic** [comment]
Я могу сделать для примера так,чтобы юзер вводил свой номер счета и ему выдавалась информация: баланс ,валюта и время совершения последней операции?Это чтобы использовать ДТО

**Comment by aandrey1993** [comment]
> 
> 
> Я могу сделать для примера так,чтобы юзер вводил свой номер счета и ему выдавалась информация: баланс ,валюта и время совершения последней операции?Это чтобы использовать ДТО

Это можно сделать и при получении списка счетов. Все полученные объекты entity из базы, можно привести в классы DTO. (Пройтись циклом по всему списку entity и заполнить по каждому элементу объект DTO, Полученный объект DTO вставляется в новый List). В итоге, полученный список возвращается из контроллера.

Если этот подход не понятен, можете сделать как вы описали для одного счета в качестве примера

**Comment by StefanBoblic** [comment]
Здравствуйте,я вроде исправил проблему ,добавил сервис для маппинга,проверил метод в сваггере,получилось что работает даже без цикла

**Comment by aandrey1993** [comment]
Маппинг составлен правильно.  Но в сервис можно было перевести все остальные методы для работы с счетами: 
- добавление счета
- удаление счета


Из контроллера бы вызывались методы сервиса., и не выполнялись обращения напрямую к базе.

**Comment by StefanBoblic** [comment]
Я понял,эти методы не были обязательны по заданию,я сделал чтобы просто проверить как они работают ,для себя

**Comment by aandrey1993** [comment]
Ок, хорошо. Я просто написал на будущее, чтобы уяснить использования репозиторий не должно быть в контроллере
